// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3x0yfnstYCl0x2frlHPQiZm9Sbl8n6cE',
    appId: '1:14212094395:web:32681948dc2a3feb42cc9e',
    messagingSenderId: '14212094395',
    projectId: 'push-notification-p3l-8a12b',
    authDomain: 'push-notification-p3l-8a12b.firebaseapp.com',
    storageBucket: 'push-notification-p3l-8a12b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDOU81rweMzManCYpeAs7F7eaizAQ95yY',
    appId: '1:14212094395:android:ef9ba508915abb2542cc9e',
    messagingSenderId: '14212094395',
    projectId: 'push-notification-p3l-8a12b',
    storageBucket: 'push-notification-p3l-8a12b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU3Av62dcttGWqRsRYGXwS1ZnBjlKfdJE',
    appId: '1:14212094395:ios:e334690dbebccfec42cc9e',
    messagingSenderId: '14212094395',
    projectId: 'push-notification-p3l-8a12b',
    storageBucket: 'push-notification-p3l-8a12b.firebasestorage.app',
    iosBundleId: 'com.example.frontendmobileP3lReusemart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU3Av62dcttGWqRsRYGXwS1ZnBjlKfdJE',
    appId: '1:14212094395:ios:e334690dbebccfec42cc9e',
    messagingSenderId: '14212094395',
    projectId: 'push-notification-p3l-8a12b',
    storageBucket: 'push-notification-p3l-8a12b.firebasestorage.app',
    iosBundleId: 'com.example.frontendmobileP3lReusemart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3x0yfnstYCl0x2frlHPQiZm9Sbl8n6cE',
    appId: '1:14212094395:web:287db1c7909ff47142cc9e',
    messagingSenderId: '14212094395',
    projectId: 'push-notification-p3l-8a12b',
    authDomain: 'push-notification-p3l-8a12b.firebaseapp.com',
    storageBucket: 'push-notification-p3l-8a12b.firebasestorage.app',
  );

}